name: CI-CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=wellmattos23_Project-FastAPI-Pipeline
            -Dsonar.organization=wellmattos23
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: |
            wmattos/fastapi:v1
            wmattos/fastapi:latest

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.24.0/trivy_0.24.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.24.0_Linux-64bit.deb

      - name: Trivy Scan
        run: |
          trivy image wmattos/fastapi:latest

      - name: Checkout Ops Repository
        uses: actions/checkout@v3
        with:
          repository: wellmattos23/Project-FastAPI-Pipeline
          ref: main

      - name: Update TAG
        run: |
          sed -i 's|image: .*|image: '"${{ secrets.USER }}/fastapi:latest"'|' deployment.yaml
          git add deployment.yaml
          git commit -m "Update Docker image TAG to latest"
          git push
