name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
       
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: .
          push: true
          tags: |
            wmattos/api-fastapi:v1
            wmattos/api-fastapi:latest
 
